// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function BrowserOpenURL(arg1) {
  return window['go']['main']['App']['BrowserOpenURL'](arg1);
}

export function BuildCapturedOpenAPI(arg1, arg2) {
  return window['go']['main']['App']['BuildCapturedOpenAPI'](arg1, arg2);
}

export function BuildReportHTMLContent(arg1) {
  return window['go']['main']['App']['BuildReportHTMLContent'](arg1);
}

export function BuildShareDoc(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BuildShareDoc'](arg1, arg2, arg3, arg4);
}

export function BuildSharedHTML(arg1, arg2) {
  return window['go']['main']['App']['BuildSharedHTML'](arg1, arg2);
}

export function BuildSharedTitle(arg1, arg2) {
  return window['go']['main']['App']['BuildSharedTitle'](arg1, arg2);
}

export function CallAI(arg1) {
  return window['go']['main']['App']['CallAI'](arg1);
}

export function CaptureInfo() {
  return window['go']['main']['App']['CaptureInfo']();
}

export function CaptureServerRunning() {
  return window['go']['main']['App']['CaptureServerRunning']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearAgentLogs() {
  return window['go']['main']['App']['ClearAgentLogs']();
}

export function ClearAgentMessages() {
  return window['go']['main']['App']['ClearAgentMessages']();
}

export function ClearCapturedRequests() {
  return window['go']['main']['App']['ClearCapturedRequests']();
}

export function ClearClipHistory() {
  return window['go']['main']['App']['ClearClipHistory']();
}

export function ClearTestData(arg1, arg2) {
  return window['go']['main']['App']['ClearTestData'](arg1, arg2);
}

export function ClipHistory() {
  return window['go']['main']['App']['ClipHistory']();
}

export function ClipboardGetText() {
  return window['go']['main']['App']['ClipboardGetText']();
}

export function ClipboardSetText(arg1) {
  return window['go']['main']['App']['ClipboardSetText'](arg1);
}

export function CloseClipboardWindow() {
  return window['go']['main']['App']['CloseClipboardWindow']();
}

export function CopyClipItem(arg1) {
  return window['go']['main']['App']['CopyClipItem'](arg1);
}

export function CopyDocMarkdown(arg1, arg2) {
  return window['go']['main']['App']['CopyDocMarkdown'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateAgentSession(arg1) {
  return window['go']['main']['App']['CreateAgentSession'](arg1);
}

export function CreateShareLink(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateShareLink'](arg1, arg2, arg3, arg4);
}

export function DeleteAgentSession(arg1) {
  return window['go']['main']['App']['DeleteAgentSession'](arg1);
}

export function DeleteClipItem(arg1) {
  return window['go']['main']['App']['DeleteClipItem'](arg1);
}

export function DeleteTestCases(arg1) {
  return window['go']['main']['App']['DeleteTestCases'](arg1);
}

export function Emit(arg1, arg2) {
  return window['go']['main']['App']['Emit'](arg1, arg2);
}

export function ExportCapturedOpenAPI(arg1, arg2) {
  return window['go']['main']['App']['ExportCapturedOpenAPI'](arg1, arg2);
}

export function ExportDoc(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportDoc'](arg1, arg2, arg3);
}

export function ExportStressReport(arg1, arg2) {
  return window['go']['main']['App']['ExportStressReport'](arg1, arg2);
}

export function ExportTestReport(arg1, arg2) {
  return window['go']['main']['App']['ExportTestReport'](arg1, arg2);
}

export function FormatJSON(arg1) {
  return window['go']['main']['App']['FormatJSON'](arg1);
}

export function GenerateApiFromCaptured(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateApiFromCaptured'](arg1, arg2, arg3);
}

export function GenerateDescriptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateDescriptions'](arg1, arg2, arg3);
}

export function GenerateReportSummary(arg1) {
  return window['go']['main']['App']['GenerateReportSummary'](arg1);
}

export function GenerateTestCases(arg1) {
  return window['go']['main']['App']['GenerateTestCases'](arg1);
}

export function GenerateTestCasesAsync(arg1) {
  return window['go']['main']['App']['GenerateTestCasesAsync'](arg1);
}

export function GenerateTestCasesForApis(arg1) {
  return window['go']['main']['App']['GenerateTestCasesForApis'](arg1);
}

export function GetBuiltinTools() {
  return window['go']['main']['App']['GetBuiltinTools']();
}

export function GetCapturedRequests() {
  return window['go']['main']['App']['GetCapturedRequests']();
}

export function GetClipImageData(arg1) {
  return window['go']['main']['App']['GetClipImageData'](arg1);
}

export function GetClipItems() {
  return window['go']['main']['App']['GetClipItems']();
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function GetDataFilePath() {
  return window['go']['main']['App']['GetDataFilePath']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportApisAsTestCases(arg1) {
  return window['go']['main']['App']['ImportApisAsTestCases'](arg1);
}

export function ImportCapturedAsTestCases(arg1) {
  return window['go']['main']['App']['ImportCapturedAsTestCases'](arg1);
}

export function ImportDoc() {
  return window['go']['main']['App']['ImportDoc']();
}

export function ListAllMCPTools() {
  return window['go']['main']['App']['ListAllMCPTools']();
}

export function ListShares() {
  return window['go']['main']['App']['ListShares']();
}

export function LoadAgentData() {
  return window['go']['main']['App']['LoadAgentData']();
}

export function LoadData() {
  return window['go']['main']['App']['LoadData']();
}

export function NotifyUpdated() {
  return window['go']['main']['App']['NotifyUpdated']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function OpenShareDoc(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OpenShareDoc'](arg1, arg2, arg3, arg4, arg5);
}

export function ParseFields(arg1, arg2) {
  return window['go']['main']['App']['ParseFields'](arg1, arg2);
}

export function PluginConnect(arg1) {
  return window['go']['main']['App']['PluginConnect'](arg1);
}

export function PluginDBDatabases(arg1) {
  return window['go']['main']['App']['PluginDBDatabases'](arg1);
}

export function PluginDBExec(arg1, arg2) {
  return window['go']['main']['App']['PluginDBExec'](arg1, arg2);
}

export function PluginDBQuery(arg1, arg2) {
  return window['go']['main']['App']['PluginDBQuery'](arg1, arg2);
}

export function PluginDBTables(arg1, arg2) {
  return window['go']['main']['App']['PluginDBTables'](arg1, arg2);
}

export function PluginDBTest(arg1) {
  return window['go']['main']['App']['PluginDBTest'](arg1);
}

export function PluginDisconnect(arg1) {
  return window['go']['main']['App']['PluginDisconnect'](arg1);
}

export function PluginESIndices(arg1) {
  return window['go']['main']['App']['PluginESIndices'](arg1);
}

export function PluginESSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginESSearch'](arg1, arg2, arg3);
}

export function PluginFTPDelete(arg1, arg2) {
  return window['go']['main']['App']['PluginFTPDelete'](arg1, arg2);
}

export function PluginFTPDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginFTPDownload'](arg1, arg2, arg3);
}

export function PluginFTPList(arg1, arg2) {
  return window['go']['main']['App']['PluginFTPList'](arg1, arg2);
}

export function PluginFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['PluginFTPMkdir'](arg1, arg2);
}

export function PluginFTPRead(arg1, arg2) {
  return window['go']['main']['App']['PluginFTPRead'](arg1, arg2);
}

export function PluginFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginFTPRename'](arg1, arg2, arg3);
}

export function PluginFTPUploadB64(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PluginFTPUploadB64'](arg1, arg2, arg3, arg4);
}

export function PluginFTPWrite(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginFTPWrite'](arg1, arg2, arg3);
}

export function PluginRedisDel(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginRedisDel'](arg1, arg2, arg3);
}

export function PluginRedisKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginRedisKeys'](arg1, arg2, arg3);
}

export function PluginRedisSet(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PluginRedisSet'](arg1, arg2, arg3, arg4, arg5);
}

export function PluginRedisTTL(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginRedisTTL'](arg1, arg2, arg3);
}

export function PluginRedisValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginRedisValue'](arg1, arg2, arg3);
}

export function PluginSFTPDelete(arg1, arg2) {
  return window['go']['main']['App']['PluginSFTPDelete'](arg1, arg2);
}

export function PluginSFTPDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginSFTPDownload'](arg1, arg2, arg3);
}

export function PluginSFTPList(arg1, arg2) {
  return window['go']['main']['App']['PluginSFTPList'](arg1, arg2);
}

export function PluginSFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['PluginSFTPMkdir'](arg1, arg2);
}

export function PluginSFTPRead(arg1, arg2) {
  return window['go']['main']['App']['PluginSFTPRead'](arg1, arg2);
}

export function PluginSFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginSFTPRename'](arg1, arg2, arg3);
}

export function PluginSFTPUploadB64(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PluginSFTPUploadB64'](arg1, arg2, arg3, arg4);
}

export function PluginSFTPWrite(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginSFTPWrite'](arg1, arg2, arg3);
}

export function PluginSSHClose(arg1) {
  return window['go']['main']['App']['PluginSSHClose'](arg1);
}

export function PluginSSHExec(arg1, arg2) {
  return window['go']['main']['App']['PluginSSHExec'](arg1, arg2);
}

export function PluginSSHInput(arg1, arg2) {
  return window['go']['main']['App']['PluginSSHInput'](arg1, arg2);
}

export function PluginSSHOpen(arg1) {
  return window['go']['main']['App']['PluginSSHOpen'](arg1);
}

export function PluginSSHResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginSSHResize'](arg1, arg2, arg3);
}

export function PluginSetClipboard(arg1) {
  return window['go']['main']['App']['PluginSetClipboard'](arg1);
}

export function PluginTest(arg1) {
  return window['go']['main']['App']['PluginTest'](arg1);
}

export function PolishText(arg1) {
  return window['go']['main']['App']['PolishText'](arg1);
}

export function QueryAgentLogs(arg1) {
  return window['go']['main']['App']['QueryAgentLogs'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadData() {
  return window['go']['main']['App']['ReadData']();
}

export function RefreshShareDoc(arg1, arg2, arg3) {
  return window['go']['main']['App']['RefreshShareDoc'](arg1, arg2, arg3);
}

export function RenameAgentSession(arg1, arg2) {
  return window['go']['main']['App']['RenameAgentSession'](arg1, arg2);
}

export function RunAgent(arg1) {
  return window['go']['main']['App']['RunAgent'](arg1);
}

export function RunStressTest(arg1, arg2) {
  return window['go']['main']['App']['RunStressTest'](arg1, arg2);
}

export function RunTestCases(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunTestCases'](arg1, arg2, arg3);
}

export function RunTestPlan(arg1) {
  return window['go']['main']['App']['RunTestPlan'](arg1);
}

export function SaveAgentConfig(arg1) {
  return window['go']['main']['App']['SaveAgentConfig'](arg1);
}

export function SaveAgentSkills(arg1) {
  return window['go']['main']['App']['SaveAgentSkills'](arg1);
}

export function SaveAgentUsers(arg1) {
  return window['go']['main']['App']['SaveAgentUsers'](arg1);
}

export function SaveClipImage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveClipImage'](arg1, arg2, arg3, arg4);
}

export function SaveClipText(arg1, arg2) {
  return window['go']['main']['App']['SaveClipText'](arg1, arg2);
}

export function SaveData(arg1) {
  return window['go']['main']['App']['SaveData'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveMCPServers(arg1) {
  return window['go']['main']['App']['SaveMCPServers'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SetClipboardText(arg1) {
  return window['go']['main']['App']['SetClipboardText'](arg1);
}

export function ShareDoc(arg1, arg2) {
  return window['go']['main']['App']['ShareDoc'](arg1, arg2);
}

export function ShareInfo() {
  return window['go']['main']['App']['ShareInfo']();
}

export function ShareServerRunning() {
  return window['go']['main']['App']['ShareServerRunning']();
}

export function ShareTestReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShareTestReport'](arg1, arg2, arg3);
}

export function ShowClipboardWindow() {
  return window['go']['main']['App']['ShowClipboardWindow']();
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function SniffCAPEM() {
  return window['go']['main']['App']['SniffCAPEM']();
}

export function SniffCAPath() {
  return window['go']['main']['App']['SniffCAPath']();
}

export function SniffDeleteSession(arg1) {
  return window['go']['main']['App']['SniffDeleteSession'](arg1);
}

export function SniffExportOpenAPI(arg1, arg2) {
  return window['go']['main']['App']['SniffExportOpenAPI'](arg1, arg2);
}

export function SniffGenerateApiFromRecords(arg1, arg2, arg3) {
  return window['go']['main']['App']['SniffGenerateApiFromRecords'](arg1, arg2, arg3);
}

export function SniffGenerateApiFromSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SniffGenerateApiFromSession'](arg1, arg2, arg3, arg4);
}

export function SniffGetSession(arg1) {
  return window['go']['main']['App']['SniffGetSession'](arg1);
}

export function SniffImportCA(arg1, arg2) {
  return window['go']['main']['App']['SniffImportCA'](arg1, arg2);
}

export function SniffInstallCA() {
  return window['go']['main']['App']['SniffInstallCA']();
}

export function SniffListSessions() {
  return window['go']['main']['App']['SniffListSessions']();
}

export function SniffPickCAFile() {
  return window['go']['main']['App']['SniffPickCAFile']();
}

export function SniffSetFilter(arg1) {
  return window['go']['main']['App']['SniffSetFilter'](arg1);
}

export function SniffSetSystemProxy(arg1) {
  return window['go']['main']['App']['SniffSetSystemProxy'](arg1);
}

export function SniffStart(arg1) {
  return window['go']['main']['App']['SniffStart'](arg1);
}

export function SniffStatus() {
  return window['go']['main']['App']['SniffStatus']();
}

export function SniffStop() {
  return window['go']['main']['App']['SniffStop']();
}

export function StartCaptureServer(arg1, arg2) {
  return window['go']['main']['App']['StartCaptureServer'](arg1, arg2);
}

export function StartClipboardCapture() {
  return window['go']['main']['App']['StartClipboardCapture']();
}

export function StartShareServer(arg1) {
  return window['go']['main']['App']['StartShareServer'](arg1);
}

export function StartSyncServer() {
  return window['go']['main']['App']['StartSyncServer']();
}

export function StopCaptureServer() {
  return window['go']['main']['App']['StopCaptureServer']();
}

export function StopClipboardCapture() {
  return window['go']['main']['App']['StopClipboardCapture']();
}

export function StopShare(arg1) {
  return window['go']['main']['App']['StopShare'](arg1);
}

export function StopShareServer() {
  return window['go']['main']['App']['StopShareServer']();
}

export function StopSyncServer() {
  return window['go']['main']['App']['StopSyncServer']();
}

export function Store() {
  return window['go']['main']['App']['Store']();
}

export function SwitchAgentSession(arg1) {
  return window['go']['main']['App']['SwitchAgentSession'](arg1);
}

export function SyncServerRunning() {
  return window['go']['main']['App']['SyncServerRunning']();
}

export function SyncServerURL() {
  return window['go']['main']['App']['SyncServerURL']();
}

export function SyncShareBackend() {
  return window['go']['main']['App']['SyncShareBackend']();
}

export function TestMCPServer(arg1) {
  return window['go']['main']['App']['TestMCPServer'](arg1);
}

export function ToolCipher(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ToolCipher'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ToolHash(arg1, arg2) {
  return window['go']['main']['App']['ToolHash'](arg1, arg2);
}

export function ToolHmac(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToolHmac'](arg1, arg2, arg3);
}

export function WindowCenter() {
  return window['go']['main']['App']['WindowCenter']();
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}

export function WindowSetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['WindowSetAlwaysOnTop'](arg1);
}

export function WindowShow() {
  return window['go']['main']['App']['WindowShow']();
}

export function WindowUnminimise() {
  return window['go']['main']['App']['WindowUnminimise']();
}
