// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyDocMarkdown(arg1:string,arg2:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateShareLink(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function ExportDoc(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FormatJSON(arg1:string):Promise<string>;

export function GenerateDescriptions(arg1:string,arg2:string,arg3:Array<main.Field>):Promise<Array<main.Field>>;

export function GetDataFilePath():Promise<string>;

export function ImportDoc():Promise<string>;

export function ListShares():Promise<Array<main.ShareInfo>>;

export function LoadData():Promise<main.AppData>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function ParseFields(arg1:string,arg2:Array<main.Field>):Promise<Array<main.Field>>;

export function SaveData(arg1:main.AppData):Promise<void>;

export function SendRequest(arg1:main.RequestSpec):Promise<main.ResponseData>;

export function ShareDoc(arg1:string,arg2:string):Promise<string>;

export function StartSyncServer(arg1:string):Promise<string>;

export function StopShare(arg1:string):Promise<void>;

export function StopSyncServer():Promise<void>;

export function SyncServerRunning():Promise<boolean>;
