// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildCapturedOpenAPI(arg1, arg2) {
  return window['go']['main']['App']['BuildCapturedOpenAPI'](arg1, arg2);
}

export function BuildReportHTMLContent(arg1) {
  return window['go']['main']['App']['BuildReportHTMLContent'](arg1);
}

export function BuildSharedHTML(arg1, arg2) {
  return window['go']['main']['App']['BuildSharedHTML'](arg1, arg2);
}

export function BuildSharedTitle(arg1, arg2) {
  return window['go']['main']['App']['BuildSharedTitle'](arg1, arg2);
}

export function CaptureInfo() {
  return window['go']['main']['App']['CaptureInfo']();
}

export function CaptureServerRunning() {
  return window['go']['main']['App']['CaptureServerRunning']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearCapturedRequests() {
  return window['go']['main']['App']['ClearCapturedRequests']();
}

export function CopyDocMarkdown(arg1, arg2) {
  return window['go']['main']['App']['CopyDocMarkdown'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateShareLink(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateShareLink'](arg1, arg2, arg3, arg4);
}

export function DeleteTestCases(arg1) {
  return window['go']['main']['App']['DeleteTestCases'](arg1);
}

export function ExportCapturedOpenAPI(arg1, arg2) {
  return window['go']['main']['App']['ExportCapturedOpenAPI'](arg1, arg2);
}

export function ExportDoc(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportDoc'](arg1, arg2, arg3);
}

export function ExportStressReport(arg1, arg2) {
  return window['go']['main']['App']['ExportStressReport'](arg1, arg2);
}

export function ExportTestReport(arg1, arg2) {
  return window['go']['main']['App']['ExportTestReport'](arg1, arg2);
}

export function FormatJSON(arg1) {
  return window['go']['main']['App']['FormatJSON'](arg1);
}

export function GenerateApiFromCaptured(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateApiFromCaptured'](arg1, arg2, arg3);
}

export function GenerateDescriptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateDescriptions'](arg1, arg2, arg3);
}

export function GenerateReportSummary(arg1) {
  return window['go']['main']['App']['GenerateReportSummary'](arg1);
}

export function GenerateTestCases(arg1) {
  return window['go']['main']['App']['GenerateTestCases'](arg1);
}

export function GenerateTestCasesAsync(arg1) {
  return window['go']['main']['App']['GenerateTestCasesAsync'](arg1);
}

export function GenerateTestCasesForApis(arg1) {
  return window['go']['main']['App']['GenerateTestCasesForApis'](arg1);
}

export function GetCapturedRequests() {
  return window['go']['main']['App']['GetCapturedRequests']();
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function GetDataFilePath() {
  return window['go']['main']['App']['GetDataFilePath']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportApisAsTestCases(arg1) {
  return window['go']['main']['App']['ImportApisAsTestCases'](arg1);
}

export function ImportCapturedAsTestCases(arg1) {
  return window['go']['main']['App']['ImportCapturedAsTestCases'](arg1);
}

export function ImportDoc() {
  return window['go']['main']['App']['ImportDoc']();
}

export function ListShares() {
  return window['go']['main']['App']['ListShares']();
}

export function LoadData() {
  return window['go']['main']['App']['LoadData']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function ParseFields(arg1, arg2) {
  return window['go']['main']['App']['ParseFields'](arg1, arg2);
}

export function PluginDBConnect(arg1) {
  return window['go']['main']['App']['PluginDBConnect'](arg1);
}

export function PluginDBDescribe(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginDBDescribe'](arg1, arg2, arg3);
}

export function PluginDBQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginDBQuery'](arg1, arg2, arg3);
}

export function PluginDBRowCount(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginDBRowCount'](arg1, arg2, arg3);
}

export function PluginDBTables(arg1, arg2) {
  return window['go']['main']['App']['PluginDBTables'](arg1, arg2);
}

export function PluginESIndices(arg1) {
  return window['go']['main']['App']['PluginESIndices'](arg1);
}

export function PluginESSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginESSearch'](arg1, arg2, arg3);
}

export function PluginFTPDelete(arg1, arg2) {
  return window['go']['main']['App']['PluginFTPDelete'](arg1, arg2);
}

export function PluginFTPDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginFTPDownload'](arg1, arg2, arg3);
}

export function PluginFTPList(arg1, arg2) {
  return window['go']['main']['App']['PluginFTPList'](arg1, arg2);
}

export function PluginFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['PluginFTPMkdir'](arg1, arg2);
}

export function PluginFTPRead(arg1, arg2) {
  return window['go']['main']['App']['PluginFTPRead'](arg1, arg2);
}

export function PluginFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginFTPRename'](arg1, arg2, arg3);
}

export function PluginFTPUploadB64(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PluginFTPUploadB64'](arg1, arg2, arg3, arg4);
}

export function PluginFTPWrite(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginFTPWrite'](arg1, arg2, arg3);
}

export function PluginRedisDel(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginRedisDel'](arg1, arg2, arg3);
}

export function PluginRedisKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginRedisKeys'](arg1, arg2, arg3);
}

export function PluginRedisSet(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PluginRedisSet'](arg1, arg2, arg3, arg4, arg5);
}

export function PluginRedisTTL(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginRedisTTL'](arg1, arg2, arg3);
}

export function PluginRedisValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginRedisValue'](arg1, arg2, arg3);
}

export function PluginSFTPDelete(arg1, arg2) {
  return window['go']['main']['App']['PluginSFTPDelete'](arg1, arg2);
}

export function PluginSFTPDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginSFTPDownload'](arg1, arg2, arg3);
}

export function PluginSFTPList(arg1, arg2) {
  return window['go']['main']['App']['PluginSFTPList'](arg1, arg2);
}

export function PluginSFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['PluginSFTPMkdir'](arg1, arg2);
}

export function PluginSFTPRead(arg1, arg2) {
  return window['go']['main']['App']['PluginSFTPRead'](arg1, arg2);
}

export function PluginSFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginSFTPRename'](arg1, arg2, arg3);
}

export function PluginSFTPUploadB64(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PluginSFTPUploadB64'](arg1, arg2, arg3, arg4);
}

export function PluginSFTPWrite(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginSFTPWrite'](arg1, arg2, arg3);
}

export function PluginSSHClose(arg1) {
  return window['go']['main']['App']['PluginSSHClose'](arg1);
}

export function PluginSSHExec(arg1, arg2) {
  return window['go']['main']['App']['PluginSSHExec'](arg1, arg2);
}

export function PluginSSHInput(arg1, arg2) {
  return window['go']['main']['App']['PluginSSHInput'](arg1, arg2);
}

export function PluginSSHOpen(arg1) {
  return window['go']['main']['App']['PluginSSHOpen'](arg1);
}

export function PluginSSHResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['PluginSSHResize'](arg1, arg2, arg3);
}

export function PluginSetClipboard(arg1) {
  return window['go']['main']['App']['PluginSetClipboard'](arg1);
}

export function PluginTest(arg1) {
  return window['go']['main']['App']['PluginTest'](arg1);
}

export function RunStressTest(arg1, arg2) {
  return window['go']['main']['App']['RunStressTest'](arg1, arg2);
}

export function RunTestCases(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunTestCases'](arg1, arg2, arg3);
}

export function RunTestPlan(arg1) {
  return window['go']['main']['App']['RunTestPlan'](arg1);
}

export function SaveData(arg1) {
  return window['go']['main']['App']['SaveData'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SetClipboardText(arg1) {
  return window['go']['main']['App']['SetClipboardText'](arg1);
}

export function ShareDoc(arg1, arg2) {
  return window['go']['main']['App']['ShareDoc'](arg1, arg2);
}

export function ShareTestReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShareTestReport'](arg1, arg2, arg3);
}

export function StartCaptureServer(arg1, arg2) {
  return window['go']['main']['App']['StartCaptureServer'](arg1, arg2);
}

export function StartSyncServer(arg1) {
  return window['go']['main']['App']['StartSyncServer'](arg1);
}

export function StopCaptureServer() {
  return window['go']['main']['App']['StopCaptureServer']();
}

export function StopShare(arg1) {
  return window['go']['main']['App']['StopShare'](arg1);
}

export function StopSyncServer() {
  return window['go']['main']['App']['StopSyncServer']();
}

export function SyncServerRunning() {
  return window['go']['main']['App']['SyncServerRunning']();
}

export function SyncServerURL() {
  return window['go']['main']['App']['SyncServerURL']();
}

export function SyncShareBackend() {
  return window['go']['main']['App']['SyncShareBackend']();
}

export function ToolCipher(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ToolCipher'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ToolHash(arg1, arg2) {
  return window['go']['main']['App']['ToolHash'](arg1, arg2);
}

export function ToolHmac(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToolHmac'](arg1, arg2, arg3);
}
