// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildCapturedOpenAPI(arg1:Array<string>,arg2:string):Promise<string>;

export function BuildReportHTMLContent(arg1:string):Promise<string>;

export function BuildSharedHTML(arg1:string,arg2:string):Promise<string>;

export function BuildSharedTitle(arg1:string,arg2:string):Promise<string>;

export function CallAI(arg1:main.CallAIArgs):Promise<string>;

export function CaptureInfo():Promise<main.CaptureServerInfo>;

export function CaptureServerRunning():Promise<boolean>;

export function CheckUpdate():Promise<main.CheckUpdateResult>;

export function ClearCapturedRequests():Promise<void>;

export function ClearClipHistory():Promise<void>;

export function ClearTestData(arg1:string,arg2:string):Promise<number>;

export function ClipHistory():Promise<Array<main.ClipItem>>;

export function CloseClipboardWindow():Promise<void>;

export function CopyClipItem(arg1:string):Promise<void>;

export function CopyDocMarkdown(arg1:string,arg2:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateShareLink(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function DeleteClipItem(arg1:string):Promise<void>;

export function DeleteTestCases(arg1:Array<string>):Promise<number>;

export function ExportCapturedOpenAPI(arg1:Array<string>,arg2:string):Promise<string>;

export function ExportDoc(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportStressReport(arg1:string,arg2:string):Promise<string>;

export function ExportTestReport(arg1:string,arg2:string):Promise<string>;

export function FormatJSON(arg1:string):Promise<string>;

export function GenerateApiFromCaptured(arg1:Array<string>,arg2:string,arg3:string):Promise<number>;

export function GenerateDescriptions(arg1:string,arg2:string,arg3:Array<main.Field>):Promise<Array<main.Field>>;

export function GenerateReportSummary(arg1:string):Promise<string>;

export function GenerateTestCases(arg1:string):Promise<Array<main.TestCase>>;

export function GenerateTestCasesAsync(arg1:Array<string>):Promise<string>;

export function GenerateTestCasesForApis(arg1:Array<string>):Promise<Array<main.TestCase>>;

export function GetCapturedRequests():Promise<Array<main.CapturedRequest>>;

export function GetClipImageData(arg1:string):Promise<Record<string, string>>;

export function GetClipItems():Promise<Array<main.ClipItem>>;

export function GetClipboardText():Promise<string>;

export function GetDataFilePath():Promise<string>;

export function GetVersion():Promise<string>;

export function ImportApisAsTestCases(arg1:Array<string>):Promise<number>;

export function ImportCapturedAsTestCases(arg1:Array<string>):Promise<number>;

export function ImportDoc():Promise<string>;

export function ListShares():Promise<Array<main.ShareInfo>>;

export function LoadData():Promise<main.AppData>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function ParseFields(arg1:string,arg2:Array<main.Field>):Promise<Array<main.Field>>;

export function PluginDBConnect(arg1:main.PluginConn):Promise<main.DBInfo>;

export function PluginDBDescribe(arg1:main.PluginConn,arg2:string,arg3:string):Promise<main.DBRow>;

export function PluginDBQuery(arg1:main.PluginConn,arg2:string,arg3:string):Promise<main.DBRow>;

export function PluginDBRowCount(arg1:main.PluginConn,arg2:string,arg3:string):Promise<number>;

export function PluginDBTables(arg1:main.PluginConn,arg2:string):Promise<Array<main.DBTable>>;

export function PluginESIndices(arg1:main.PluginConn):Promise<Array<main.ESIndex>>;

export function PluginESSearch(arg1:main.PluginConn,arg2:string,arg3:string):Promise<string>;

export function PluginFTPDelete(arg1:main.PluginConn,arg2:string):Promise<void>;

export function PluginFTPDownload(arg1:main.PluginConn,arg2:string,arg3:string):Promise<string>;

export function PluginFTPList(arg1:main.PluginConn,arg2:string):Promise<Array<main.FileInfo>>;

export function PluginFTPMkdir(arg1:main.PluginConn,arg2:string):Promise<void>;

export function PluginFTPRead(arg1:main.PluginConn,arg2:string):Promise<string>;

export function PluginFTPRename(arg1:main.PluginConn,arg2:string,arg3:string):Promise<void>;

export function PluginFTPUploadB64(arg1:main.PluginConn,arg2:string,arg3:string,arg4:string):Promise<void>;

export function PluginFTPWrite(arg1:main.PluginConn,arg2:string,arg3:string):Promise<void>;

export function PluginRedisDel(arg1:main.PluginConn,arg2:string,arg3:number):Promise<void>;

export function PluginRedisKeys(arg1:main.PluginConn,arg2:string,arg3:number):Promise<Array<main.RedisKey>>;

export function PluginRedisSet(arg1:main.PluginConn,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function PluginRedisTTL(arg1:main.PluginConn,arg2:string,arg3:number):Promise<number>;

export function PluginRedisValue(arg1:main.PluginConn,arg2:string,arg3:number):Promise<main.RedisValue>;

export function PluginSFTPDelete(arg1:main.PluginConn,arg2:string):Promise<void>;

export function PluginSFTPDownload(arg1:main.PluginConn,arg2:string,arg3:string):Promise<string>;

export function PluginSFTPList(arg1:main.PluginConn,arg2:string):Promise<Array<main.FileInfo>>;

export function PluginSFTPMkdir(arg1:main.PluginConn,arg2:string):Promise<void>;

export function PluginSFTPRead(arg1:main.PluginConn,arg2:string):Promise<string>;

export function PluginSFTPRename(arg1:main.PluginConn,arg2:string,arg3:string):Promise<void>;

export function PluginSFTPUploadB64(arg1:main.PluginConn,arg2:string,arg3:string,arg4:string):Promise<void>;

export function PluginSFTPWrite(arg1:main.PluginConn,arg2:string,arg3:string):Promise<void>;

export function PluginSSHClose(arg1:string):Promise<void>;

export function PluginSSHExec(arg1:main.PluginConn,arg2:string):Promise<string>;

export function PluginSSHInput(arg1:string,arg2:string):Promise<void>;

export function PluginSSHOpen(arg1:main.PluginConn):Promise<string>;

export function PluginSSHResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PluginSetClipboard(arg1:string):Promise<void>;

export function PluginTest(arg1:main.PluginConn):Promise<main.PluginOpResult>;

export function RunStressTest(arg1:Array<main.StressTarget>,arg2:main.StressConfig):Promise<main.StressReport>;

export function RunTestCases(arg1:Array<string>,arg2:string,arg3:number):Promise<main.TestReport>;

export function RunTestPlan(arg1:string):Promise<main.TestReport>;

export function SaveData(arg1:main.AppData):Promise<void>;

export function SendRequest(arg1:main.RequestSpec):Promise<main.ResponseData>;

export function SetClipboardText(arg1:string):Promise<void>;

export function ShareDoc(arg1:string,arg2:string):Promise<string>;

export function ShareTestReport(arg1:string,arg2:string,arg3:number):Promise<string>;

export function ShowClipboardWindow():Promise<void>;

export function StartCaptureServer(arg1:string,arg2:string):Promise<string>;

export function StartClipboardCapture():Promise<void>;

export function StartSyncServer(arg1:string):Promise<string>;

export function StopCaptureServer():Promise<void>;

export function StopClipboardCapture():Promise<void>;

export function StopShare(arg1:string):Promise<void>;

export function StopSyncServer():Promise<void>;

export function SyncServerRunning():Promise<boolean>;

export function SyncServerURL():Promise<string>;

export function SyncShareBackend():Promise<main.ShareBackend>;

export function ToolCipher(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<main.ToolResult>;

export function ToolHash(arg1:string,arg2:string):Promise<main.ToolResult>;

export function ToolHmac(arg1:string,arg2:string,arg3:string):Promise<main.ToolResult>;
