// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {capture} from '../models';
import {model} from '../models';
import {agent} from '../models';
import {share} from '../models';
import {frontend} from '../models';
import {plugins} from '../models';
import {stress} from '../models';
import {store} from '../models';
import {sync} from '../models';

export function AppVersion():Promise<string>;

export function BrowserOpenURL(arg1:string):Promise<void>;

export function BuildCapturedOpenAPI(arg1:Array<string>,arg2:string):Promise<string>;

export function BuildReportHTMLContent(arg1:string):Promise<string>;

export function BuildShareDoc(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function BuildSharedHTML(arg1:string,arg2:string):Promise<string>;

export function BuildSharedTitle(arg1:string,arg2:string):Promise<string>;

export function CallAI(arg1:main.CallAIArgs):Promise<string>;

export function CaptureInfo():Promise<capture.CaptureServerInfo>;

export function CaptureServerRunning():Promise<boolean>;

export function CheckUpdate():Promise<main.CheckUpdateResult>;

export function ClearAgentLogs():Promise<void>;

export function ClearAgentMessages():Promise<void>;

export function ClearCapturedRequests():Promise<void>;

export function ClearClipHistory():Promise<void>;

export function ClearTestData(arg1:string,arg2:string):Promise<number>;

export function ClipHistory():Promise<Array<model.ClipItem>>;

export function ClipboardGetText():Promise<string>;

export function ClipboardSetText(arg1:string):Promise<void>;

export function CloseClipboardWindow():Promise<void>;

export function CopyClipItem(arg1:string):Promise<void>;

export function CopyDocMarkdown(arg1:string,arg2:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateAgentSession(arg1:string):Promise<string>;

export function CreateShareLink(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function DeleteAgentSession(arg1:string):Promise<void>;

export function DeleteClipItem(arg1:string):Promise<void>;

export function DeleteTestCases(arg1:Array<string>):Promise<number>;

export function Emit(arg1:string,arg2:Array<any>):Promise<void>;

export function ExportCapturedOpenAPI(arg1:Array<string>,arg2:string):Promise<string>;

export function ExportDoc(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportStressReport(arg1:string,arg2:string):Promise<string>;

export function ExportTestReport(arg1:string,arg2:string):Promise<string>;

export function FormatJSON(arg1:string):Promise<string>;

export function GenerateApiFromCaptured(arg1:Array<string>,arg2:string,arg3:string):Promise<number>;

export function GenerateDescriptions(arg1:string,arg2:string,arg3:Array<model.Field>):Promise<Array<model.Field>>;

export function GenerateReportSummary(arg1:string):Promise<string>;

export function GenerateTestCases(arg1:string):Promise<Array<model.TestCase>>;

export function GenerateTestCasesAsync(arg1:Array<string>):Promise<string>;

export function GenerateTestCasesForApis(arg1:Array<string>):Promise<Array<model.TestCase>>;

export function GetBuiltinTools():Promise<Array<agent.BuiltinToolDef>>;

export function GetCapturedRequests():Promise<Array<capture.CapturedRequest>>;

export function GetClipImageData(arg1:string):Promise<Record<string, string>>;

export function GetClipItems():Promise<Array<model.ClipItem>>;

export function GetClipboardText():Promise<string>;

export function GetDataFilePath():Promise<string>;

export function GetVersion():Promise<string>;

export function ImportApisAsTestCases(arg1:Array<string>):Promise<number>;

export function ImportCapturedAsTestCases(arg1:Array<string>):Promise<number>;

export function ImportDoc():Promise<string>;

export function ListAllMCPTools():Promise<Array<agent.MCPTool>>;

export function ListShares():Promise<Array<share.ShareItemView>>;

export function LoadAgentData():Promise<agent.AgentData>;

export function LoadData():Promise<model.AppData>;

export function NotifyUpdated():Promise<void>;

export function OpenDirectoryDialog(arg1:frontend.OpenDialogOptions):Promise<string>;

export function OpenFileDialog(arg1:frontend.OpenDialogOptions):Promise<string>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OpenShareDoc(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ParseFields(arg1:string,arg2:Array<model.Field>):Promise<Array<model.Field>>;

export function PluginConnect(arg1:model.PluginConn):Promise<plugins.PluginOpResult>;

export function PluginDBDatabases(arg1:model.PluginConn):Promise<plugins.DBInfo>;

export function PluginDBExec(arg1:model.PluginConn,arg2:plugins.DBExecReq):Promise<number>;

export function PluginDBQuery(arg1:model.PluginConn,arg2:plugins.DBQueryReq):Promise<plugins.DBRow>;

export function PluginDBTables(arg1:model.PluginConn,arg2:string):Promise<Array<plugins.DBTable>>;

export function PluginDBTest(arg1:model.PluginConn):Promise<plugins.PluginOpResult>;

export function PluginDisconnect(arg1:model.PluginConn):Promise<plugins.PluginOpResult>;

export function PluginESIndices(arg1:model.PluginConn):Promise<Array<plugins.ESIndex>>;

export function PluginESSearch(arg1:model.PluginConn,arg2:string,arg3:string):Promise<string>;

export function PluginFTPDelete(arg1:model.PluginConn,arg2:string):Promise<void>;

export function PluginFTPDownload(arg1:model.PluginConn,arg2:string,arg3:string):Promise<string>;

export function PluginFTPList(arg1:model.PluginConn,arg2:string):Promise<Array<plugins.FileInfo>>;

export function PluginFTPMkdir(arg1:model.PluginConn,arg2:string):Promise<void>;

export function PluginFTPRead(arg1:model.PluginConn,arg2:string):Promise<string>;

export function PluginFTPRename(arg1:model.PluginConn,arg2:string,arg3:string):Promise<void>;

export function PluginFTPUploadB64(arg1:model.PluginConn,arg2:string,arg3:string,arg4:string):Promise<void>;

export function PluginFTPWrite(arg1:model.PluginConn,arg2:string,arg3:string):Promise<void>;

export function PluginRedisDel(arg1:model.PluginConn,arg2:string,arg3:number):Promise<void>;

export function PluginRedisKeys(arg1:model.PluginConn,arg2:string,arg3:number):Promise<Array<plugins.RedisKey>>;

export function PluginRedisSet(arg1:model.PluginConn,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function PluginRedisTTL(arg1:model.PluginConn,arg2:string,arg3:number):Promise<number>;

export function PluginRedisValue(arg1:model.PluginConn,arg2:string,arg3:number):Promise<plugins.RedisValue>;

export function PluginSFTPDelete(arg1:model.PluginConn,arg2:string):Promise<void>;

export function PluginSFTPDownload(arg1:model.PluginConn,arg2:string,arg3:string):Promise<string>;

export function PluginSFTPList(arg1:model.PluginConn,arg2:string):Promise<Array<plugins.FileInfo>>;

export function PluginSFTPMkdir(arg1:model.PluginConn,arg2:string):Promise<void>;

export function PluginSFTPRead(arg1:model.PluginConn,arg2:string):Promise<string>;

export function PluginSFTPRename(arg1:model.PluginConn,arg2:string,arg3:string):Promise<void>;

export function PluginSFTPUploadB64(arg1:model.PluginConn,arg2:string,arg3:string,arg4:string):Promise<void>;

export function PluginSFTPWrite(arg1:model.PluginConn,arg2:string,arg3:string):Promise<void>;

export function PluginSSHClose(arg1:string):Promise<void>;

export function PluginSSHExec(arg1:model.PluginConn,arg2:string):Promise<string>;

export function PluginSSHInput(arg1:string,arg2:string):Promise<void>;

export function PluginSSHOpen(arg1:model.PluginConn):Promise<string>;

export function PluginSSHResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PluginSetClipboard(arg1:string):Promise<void>;

export function PluginTest(arg1:model.PluginConn):Promise<plugins.PluginOpResult>;

export function PolishText(arg1:agent.RunAgentArgs):Promise<string>;

export function QueryAgentLogs(arg1:agent.QueryAgentLogsArgs):Promise<Array<agent.AgentLog>>;

export function Quit():Promise<void>;

export function ReadData():Promise<model.AppData>;

export function RefreshShareDoc(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameAgentSession(arg1:string,arg2:string):Promise<void>;

export function RunAgent(arg1:agent.RunAgentArgs):Promise<agent.RunAgentResult>;

export function RunStressTest(arg1:Array<stress.StressTarget>,arg2:stress.StressConfig):Promise<stress.StressReport>;

export function RunTestCases(arg1:Array<string>,arg2:string,arg3:number):Promise<model.TestReport>;

export function RunTestPlan(arg1:string):Promise<model.TestReport>;

export function SaveAgentConfig(arg1:agent.AgentConfig):Promise<void>;

export function SaveAgentSkills(arg1:Array<agent.AgentSkill>):Promise<void>;

export function SaveAgentUsers(arg1:Array<agent.AgentUser>):Promise<void>;

export function SaveClipImage(arg1:Array<number>,arg2:number,arg3:number,arg4:string):Promise<void>;

export function SaveClipText(arg1:string,arg2:string):Promise<void>;

export function SaveData(arg1:model.AppData):Promise<void>;

export function SaveFileDialog(arg1:frontend.SaveDialogOptions):Promise<string>;

export function SaveMCPServers(arg1:Array<agent.MCPServer>):Promise<void>;

export function SendRequest(arg1:model.RequestSpec):Promise<model.ResponseData>;

export function SetClipboardText(arg1:string):Promise<void>;

export function ShareDoc(arg1:string,arg2:string):Promise<string>;

export function ShareInfo():Promise<share.ShareServerInfo>;

export function ShareServerRunning():Promise<boolean>;

export function ShareTestReport(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ShowClipboardWindow():Promise<void>;

export function ShowMainWindow():Promise<void>;

export function StartCaptureServer(arg1:string,arg2:string):Promise<string>;

export function StartClipboardCapture():Promise<void>;

export function StartShareServer(arg1:string):Promise<void>;

export function StartSyncServer():Promise<string>;

export function StopCaptureServer():Promise<void>;

export function StopClipboardCapture():Promise<void>;

export function StopShare(arg1:string):Promise<void>;

export function StopShareServer():Promise<void>;

export function StopSyncServer():Promise<void>;

export function Store():Promise<store.Store>;

export function SwitchAgentSession(arg1:string):Promise<void>;

export function SyncServerRunning():Promise<boolean>;

export function SyncServerURL():Promise<string>;

export function SyncShareBackend():Promise<sync.ShareBackend>;

export function TestMCPServer(arg1:agent.MCPServer):Promise<Array<agent.MCPTool>>;

export function ToolCipher(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<main.ToolResult>;

export function ToolHash(arg1:string,arg2:string):Promise<main.ToolResult>;

export function ToolHmac(arg1:string,arg2:string,arg3:string):Promise<main.ToolResult>;

export function WindowCenter():Promise<void>;

export function WindowHide():Promise<void>;

export function WindowSetAlwaysOnTop(arg1:boolean):Promise<void>;

export function WindowShow():Promise<void>;

export function WindowUnminimise():Promise<void>;
